services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./LevelUP-frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - project-level-up_default

networks:
  project-level-up_default:
    external: true