version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev  # Path to backend Dockerfile
    env_file:
      - .env
    environment:
      - ENV=development  # Can switch to production for deployment
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount backend code for development
    depends_on:
      - database  # Required if database is used

  frontend:
    build:
      context: .
      dockerfile: frontend/LevelUP-frontend/Dockerfile.dev  # Path to frontend Dockerfile
    ports:
      - "3000:80"  # Expose NGINX on port 3000 for production
    volumes:
      - ./frontend/LevelUP-frontend:/app  # Only if hot-reloading is enabled in dev mode
    depends_on:
      - backend

  # Optional database service
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: level_up_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
