services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=sqlite:////app/data/level_up.db
      - ENV=${ENV}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REPOSITORY=${REPOSITORY}
    command: flask run --host=0.0.0.0 --port=5000  # Change to Gunicorn for production
    networks:
      - project-level-up_default

networks:
  project-level-up_default:
    external: true