services:
  app:
    build: .
    volumes:
     - .:/app
    ports:
      - "5000:5000"
    environment:
      - ENV=${ENV} # Using .env file
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:///data/level_up.db