# Use the official lightweight Python image.
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY backend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Set environment variables to indicate development mode
ENV ENV=development

# Command to run the app with SocketIO in development mode
CMD ["python", "app.py"]
